### PR TITLE
(untested) use kodi file handling

### PR DESCRIPTION
**Pull request by notspiff**
now this can read from the VFS (network and such).

this is completely untested, but in principle the lib can now read from the kodi vfs.

### CODE REVIEW

**Comment by mapfau** [comment]
4>C:\Dev\kodi_addons\inputstream.mpd\lib\libbento4\System\Kodi\Ap4KodiFileByteStream.cpp(126): error C2039: 'OpenForWrite' : is not a member of 'ADDON::CHelper_libXBMC_addon' [C:\Dev\xbmc\project\cmake\addons\build\inputstream.mpd-prefix\src\inputstream.mpd-build\lib\libbento4\bento4.vcxproj]
4>C:\Dev\kodi_addons\inputstream.mpd\lib\libbento4\System\Kodi\Ap4KodiFileByteStream.cpp(130): error C2039: 'OpenForWrite' : is not a member of 'ADDON::CHelper_libXBMC_addon' [C:\Dev\xbmc\project\cmake\addons\build\inputstream.mpd-prefix\src\inputstream.mpd-build\lib\libbento4\bento4.vcxproj]
4>C:\Dev\kodi_addons\inputstream.mpd\lib\libbento4\System\Kodi\Ap4KodiFileByteStream.cpp(141): error C2039: 'FileLength' : is not a member of 'ADDON::CHelper_libXBMC_addon' [C:\Dev\xbmc\project\cmake\addons\build\inputstream.mpd-prefix\src\inputstream.mpd-build\lib\libbento4\bento4.vcxproj]
4>C:\Dev\kodi_addons\inputstream.mpd\lib\libbento4\System\Kodi\Ap4KodiFileByteStream.cpp(158): error C2440: 'initializing' : cannot convert from 'void *' to 'FILE *' [C:\Dev\xbmc\project\cmake\addons\build\inputstream.mpd-prefix\src\inputstream.mpd-build\lib\libbento4\bento4.vcxproj]
4>C:\Dev\kodi_addons\inputstream.mpd\lib\libbento4\System\Kodi\Ap4KodiFileByteStream.cpp(158): error C2439: 'AP4_KodiFileByteStream::m_File' : member could not be initialized [C:\Dev\xbmc\project\cmake\addons\build\inputstream.mpd-prefix\src\inputstream.mpd-build\lib\libbento4\bento4.vcxproj]
4>C:\Dev\kodi_addons\inputstream.mpd\lib\libbento4\System\Kodi\Ap4KodiFileByteStream.cpp(205): error C2065: 'bytestoRead' : undeclared identifier [C:\Dev\xbmc\project\cmake\addons\build\inputstream.mpd-prefix\src\inputstream.mpd-build\lib\libbento4\bento4.vcxproj]
4>  

in my windows build.
Are there changes in kodi interface wich has to be merged also?

**Comment by akva2** [comment]
when i said untested, i meant untested  ;) written in the blind waiting for some computations. errors should be trivial;

it's xbmc->OpenFileForWrite(...) not xbmc->OpenForWrite
it's xbmc->GetFileLength(...) not xbmc->FileLength
change the m_File member to void*

**Comment by mapfau** [comment]
I see a difference in untested and "never compiled) :-) Thanx nevertheless

**Comment by mapfau** [comment]
Just for my interest: Have you worked before with Bento4? Or just looked on it and did it?

**Comment by notspiff** [comment]
latter. i was just curious if there was a file input layer in there, found
it, and did the code at the as i studied how it worked.
note that it can do http for you so you can do the same to skip the curl
usage in the dash code if you prefer, both for segments and manifests. one
good thing about that is that it would tap into the kodi cache layer.

**Comment by mapfau** [comment]
impressing! Yes this was exactly what I was thinking about when I saw your implementation: removing the Curl stuff. I'll separate the pure file part from dash into an separate class to allow both, a curl implementation and a kodi implementation and / or whatever.
But before I want to see some video frames and want to hear some sound coming out of kodi :-)

**Pull request merged**
